version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/" # Root directory where build.gradle is located
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.springframework.boot"
        versions: ["3.3.x", "3.4.x"]  # Prevents automatic Spring Boot updates beyond 3.2.x
      - dependency-name: "org.springframework:spring-core"
        versions: ["6.1.x"]  # Ensures compatibility with Spring Boot 3.2.x
      - dependency-name: "org.springdoc:springdoc-openapi-starter-webmvc-ui"
        versions: ["2.7.x", "2.8.x"]  # Keeps it at 2.6.x, since newer versions caused issues
      - dependency-name: "org.mockito:mockito-core"
        versions: ["5.11.x"]  # Prevents potential breaking changes in latest Mockito
      - dependency-name: "jakarta.persistence:jakarta.persistence-api"
        versions: ["3.2.x"]  # Keeps it at 3.1.0 for compatibility
      - dependency-name: "jakarta.validation:jakarta.validation-api"
        versions: ["3.1.x"]  # Keeps it at 3.0.2 for compatibility
      - dependency-name: "io.swagger.core.v3:swagger-annotations"
        versions: ["2.3.x"]  # Keeps it at 2.2.28
    reviewers:
      - "craigkilpatrick" # Auto-assign PRs to a reviewer
    assignees:
      - "craigkilpatrick" # Auto-assign issues to a user
    labels:
      - "dependencies"
      - "gradle"
