name: Dependency Check

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at midnight

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Run Dependency Check
        id: dependency-check
        run: |
          ./gradlew dependencies --no-daemon | tee dependencies.txt
          if grep -E "/(?i)-?(alpha|beta|rc|m[0-9]+|snapshot)[.\d-]*/)" dependencies.txt; then
            echo "❌ Unstable dependency found!"
            exit 1
          fi

      - name: Build Project
        run: ./gradlew build --no-daemon

  close-failed-pr:
    needs: dependency-check
    if: failure() && github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ❌ This Dependabot PR contains unstable dependencies and has failed validation.
            It will be automatically closed. Please check dependency requirements before reopening.

      - name: Close PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              state: "closed"
            })
